language: ruby
rvm:
  - 2.6
services:
  - postgresql
addons:
  postgresql: "9.5"
env:
  matrix:
    - DATABASE_ADAPTER=sqlite DATABASE_NAME=pact_broker_database.sqlite3
    - DATABASE_ADAPTER=postgres DATABASE_NAME=pact_broker
before_script:
  - psql -U postgres -c "CREATE DATABASE pact_broker;"
script:
  - example/issue-old.sh
  - example/issue-new.sh
