language: ruby
rvm:
  # - 2.2.7
  # - 2.3.4
  - 2.4.1
services:
  - postgresql
  - mysql
addons:
  postgresql: "9.6"
env:
  - DATABASE_ADAPTER=default RUBYOPT="-W0"
  - DATABASE_ADAPTER=postgres RUBYOPT="-W0"
  - DATABASE_ADAPTER=mysql RUBYOPT="-W0"
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -U postgres -c "CREATE DATABASE pact_broker;"
  - mysql -e 'CREATE DATABASE pact_broker;'
script:
  - bundle exec rake
