# This doesn't work yet
version: "3"

services:
  tests:
    build: .
    ports:
      - "9292:9292"
    depends_on:
      - mysql
    environment:
      DATABASE_ADAPTER: docker_compose_mysql
      PACT_BROKER_HIDE_PACTFLOW_MESSAGES: 'true'
      INSTALL_MYSQL: 'true'
    volumes:
      - ./lib:/home/lib
      - ./spec:/home/spec
      - ./db:/home/db
      - ./config.ru:/home/config.ru
      - ./tasks:/home/tasks
      - ./Rakefile:/home/Rakefile
      - ./config:/home/config
      - ./.rspec:/home/.rspec
      - ./.rubocop:/home/.rubocop
      - ./.gitignore:/home/.gitignore

  mysql:
    image: mysql:5.7.28
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pact_broker
      MYSQL_DATABASE: pact_broker
      MYSQL_USER: pact_broker
      MYSQL_PASSWORD: pact_broker
    ports:
      - "3306:3306"
