# This doesn't work yet
version: "3"

services:
  tests:
    build: .
    command: sh -c "sleep 10 && bundle exec rake db:prepare:test && bundle exec rspec spec/lib/pact_broker/domain/version_spec.rb"
    depends_on:
      - mysql
    environment:
      RACK_ENV: test
      DATABASE_ADAPTER: docker_compose_mysql
      PACT_BROKER_DATABASE_USERNAME: pact_broker
      PACT_BROKER_DATABASE_PASSWORD: pact_broker
      PACT_BROKER_DATABASE_HOST: pact_broker
      PACT_BROKER_DATABASE_NAME: pact_broker
      PACT_BROKER_BASIC_AUTH_USERNAME: pact_broker
      PACT_BROKER_BASIC_AUTH_PASSWORD: pact_broker
      PACT_BROKER_PORT: "9292"
    volumes:
        - ${PWD}:/app

  mysql:
    image: mysql:5.7.28
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pact_broker
      MYSQL_DATABASE: pact_broker
      MYSQL_USER: pact_broker
      MYSQL_PASSWORD: pact_broker
    ports:
      - "3306:3306"
