default: &default
  adapter: sqlite
  database: db/pact_broker_database.sqlite3

test:
  <<: *default
  database: tmp/pact_broker_database_test.sqlite3

# test:
#   adapter: "postgres"
#   database: "pact_broker"
#   username: 'pact_broker'
#   password: 'pact_broker'
#   encoding: 'utf8'

development:
  <<: *default

production:
  <<: *default