groups:
  - title: Logging
    vars:
      log_level:
        description: "The application log level"
        default: info
        allowed_values:
          - debug
          - info
          - warn
          - error
          - fatal
      log_format:
        description: "The application log format. Can be any value supported by Semantic Logger."
        default: "default"
        allowed_values:
          - default
          - json
          - color
        more_info: https://github.com/rocketjob/semantic_logger/tree/master/lib/semantic_logger/formatters
      log_dir:
        description: "The log file directory"
        default: "./logs"
      log_stream:
        description: "The stream to which the logs will be sent. Set to `stdout` to stream to standard out."
        default: "file"
        allowed_values:
          - stdout
          - file
  - title: Authentication and authorization
    comments: |
      The Pact Broker comes with 2 configurable basic auth users - one with read/write privileges, and one with read only privileges.
      The read only credentials should be distributed to the developers for use from development machines, and the read/write credentials
      should be used for CI/CD.
    vars:
      basic_auth_enabled:
        description: "Whether to enabled basic authorization"
        default: false
        allowed_values:
          - true
          - false
      basic_auth_username:
        description: "The username for the read/write basic auth user"
      basic_auth_password:
        description: "The password for the read/write basic auth user"
      basic_auth_read_only_username:
        description: "The username for the read only basic auth user"
      basic_auth_read_only_password:
        description: "The password for the read only basic auth user"
      allow_public_read:
        description: "If you want to allow public read access, but still require credentials for writing, then leave `basic_auth_read_only_username` and `basic_auth_read_only_password` unset, and set `allow_public_read` to `true`"
        default: false
        allowed_values:
          - true
          - false
      public_heartbeat:
        description: "If you have enabled basic auth, but require unauthenticated access to the heartbeat URL (eg. for use within an AWS autoscaling group), set `public_heartbeat` to `true`"
        default: false
        allowed_values:
          - true
          - false
  - title: TODO
    vars:

      warning_error_class_names:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      hide_pactflow_messages:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      webhook_retry_schedule:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      webhook_http_method_whitelist:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      webhook_http_code_success:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      webhook_scheme_whitelist:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      webhook_host_whitelist:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      disable_ssl_verification:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      user_agent:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      port:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      base_url:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      base_urls:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      use_hal_browser:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      enable_diagnostic_endpoints:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      use_rack_protection:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      badge_provider_mode:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      enable_public_badge_access:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      shields_io_base_url:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      use_case_sensitive_resource_names:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      order_versions_by_date:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      base_equality_only_on_content_that_affects_verification_results:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      check_for_potential_duplicate_pacticipant_names:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      create_deployed_versions_for_tags:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      use_first_tag_as_branch:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      use_first_tag_as_branch_time_limit:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      semver_formats:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
      features:
        description: ""
        default:
        allowed_values:
          - todo
        more_info: null
